local M = {}
M.rules = {
    ["typescript:S101"] = { level = "on", parameters = { format = "^[A-Z][a-zA-Z0-9]*$" } },
    ["typescript:S103"] = { level = "on", parameters = { maximumLineLength = 180 } },
    ["typescript:S104"] = { level = "on", parameters = { maximum = 1000 } },
    ["typescript:S106"] = { level = "on" },
    ["typescript:S107"] = { level = "on", parameters = { maximumFunctionParameters = 7 } },
    ["typescript:S108"] = { level = "on" },
    ["typescript:S1110"] = { level = "on" },
    ["typescript:S1116"] = { level = "on" },
    ["typescript:S1125"] = { level = "on" },
    ["typescript:S1143"] = { level = "on" },
    ["typescript:S117"] = {
        level = "on",
        parameters = {
            format = "^[_$A-Za-z][$A-Za-z0-9]*$|^[_$A-Z][_$A-Z0-9]+$",
        },
    },
    ["typescript:S1192"] = { level = "on", parameters = { threshold = 3 } },
    ["typescript:S122"] = { level = "on" },
    ["typescript:S1226"] = { level = "on" },
    ["typescript:S125"] = { level = "on" },
    ["typescript:S1264"] = { level = "on" },
    ["typescript:S1301"] = { level = "on" },
    ["typescript:S138"] = { level = "on", parameters = { max = 200 } },
    ["typescript:S1439"] = { level = "on" },
    ["typescript:S1440"] = { level = "on" },
    ["typescript:S1479"] = { level = "on", parameters = { maximum = 30 } },
    ["typescript:S1488"] = { level = "on" },
    ["typescript:S1516"] = { level = "on" },
    ["typescript:S1523"] = { level = "on" },
    ["typescript:S1525"] = { level = "on" },
    ["typescript:S1526"] = { level = "on" },
    ["typescript:S1533"] = { level = "on" },
    ["typescript:S1656"] = { level = "on" },
    ["typescript:S1751"] = { level = "on" },
    ["typescript:S1764"] = { level = "on" },
    ["typescript:S1821"] = { level = "on" },
    ["typescript:S1854"] = { level = "on" },
    ["typescript:S1862"] = { level = "on" },
    ["typescript:S1871"] = { level = "on" },
    ["typescript:S1874"] = { level = "on" },
    ["typescript:S1940"] = { level = "on" },
    ["typescript:S2068"] = {
        level = "on",
        parameters = {
            credentialWords = { "password", "pwd", "passwd" },
        },
    },
    ["typescript:S2123"] = { level = "on" },
    ["typescript:S2201"] = { level = "on" },
    ["typescript:S2234"] = { level = "on" },
    ["typescript:S2589"] = { level = "on" },
    ["typescript:S2681"] = { level = "on" },
    ["typescript:S2685"] = { level = "on" },
    ["typescript:S2688"] = { level = "on" },
    ["typescript:S2737"] = { level = "on" },
    ["typescript:S2757"] = { level = "on" },
    ["typescript:S2814"] = { level = "on" },
    ["typescript:S2870"] = { level = "on" },
    ["typescript:S2871"] = { level = "on" },
    ["typescript:S2933"] = { level = "on" },
    ["typescript:S2966"] = { level = "on" },
    ["typescript:S3257"] = { level = "on" },
    ["typescript:S3353"] = { level = "on" },
    ["typescript:S3504"] = { level = "on" },
    ["typescript:S3512"] = { level = "on" },
    ["typescript:S3516"] = { level = "on" },
    ["typescript:S3533"] = { level = "on" },
    ["typescript:S3616"] = { level = "on" },
    ["typescript:S3626"] = { level = "on" },
    ["typescript:S3696"] = { level = "on" },
    ["typescript:S3699"] = { level = "on" },
    ["typescript:S3776"] = { level = "on", parameters = { threshold = 15 } },
    ["typescript:S3786"] = { level = "on" },
    ["typescript:S3799"] = { level = "on" },
    ["typescript:S3801"] = { level = "on" },
    ["typescript:S3854"] = { level = "on" },
    ["typescript:S3863"] = { level = "on" },
    ["typescript:S3923"] = { level = "on" },
    ["typescript:S3972"] = { level = "on" },
    ["typescript:S3981"] = { level = "on" },
    ["typescript:S3984"] = { level = "on" },
    ["typescript:S4030"] = { level = "on" },
    ["typescript:S4043"] = { level = "on" },
    ["typescript:S4123"] = { level = "on" },
    ["typescript:S4124"] = { level = "on" },
    ["typescript:S4136"] = { level = "on" },
    ["typescript:S4137"] = { level = "on" },
    ["typescript:S4138"] = { level = "on" },
    ["typescript:S4139"] = { level = "on" },
    ["typescript:S4140"] = { level = "on" },
    ["typescript:S4143"] = { level = "on" },
    ["typescript:S4144"] = { level = "on" },
    ["typescript:S4156"] = { level = "on" },
    ["typescript:S4157"] = { level = "on" },
    ["typescript:S4158"] = { level = "on" },
    ["typescript:S4275"] = { level = "on" },
    ["typescript:S4322"] = { level = "on" },
    ["typescript:S4323"] = { level = "on" },
    ["typescript:S4325"] = { level = "on" },
    ["typescript:S4326"] = { level = "on" },
    ["typescript:S4327"] = { level = "on" },
    ["typescript:S4328"] = { level = "on" },
    ["typescript:S4335"] = { level = "on" },
    ["typescript:S4524"] = { level = "on" },
    ["typescript:S4619"] = { level = "on" },
    ["typescript:S4621"] = { level = "on" },
    ["typescript:S4623"] = { level = "on" },
    ["typescript:S4624"] = { level = "on" },
    ["typescript:S4634"] = { level = "on" },
    ["typescript:S4782"] = { level = "on" },
    ["typescript:S4798"] = { level = "on" },
    ["typescript:S4822"] = { level = "on" },
    ["typescript:S878"] = { level = "on" },
    ["typescript:S881"] = { level = "on" },
    ["typescript:S905"] = { level = "on" },
}
return M
